d3.select("#block")
  .transition()
  .duration(500)
  .delay(750)
  .ease(d3.easeBounceOut)
  .style("width", "400px")
  .transition()
  .duration(500)
  .delay(750)
  .ease(d3.easeBounceOut)
  .style("height", "600px")
  .style("background-color", "pink");
